### ISSUE TITLE
[FEATURE] add tooltip for socials and dark/light mode icon.

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#104]
## Description

- User might occasionally be unfamiliar with the icon user for.
- In these situations, having a tooltip for social icons and icons in dark/light modes will be helpful.
- So, add `Tooltip` for socials and dark/light mode theme icon.

## For reference:
![Screenshot 2022-09-08 234847](https://user-images.githubusercontent.com/107752425/189196598-1081f5a2-db29-4841-b0ce-8d1b6a0ec7ac.png)

**Comment by rohitdasu** [comment]
so basically add tooltips for the below icons only in the navbar

<img width="169" alt="Screenshot 2022-09-08 at 11 59 14 PM" src="https://user-images.githubusercontent.com/48400770/189198524-922b7401-7fb6-4c4c-80c5-7794e44421a5.png">

**Comment by RakeshSangem** [comment]
> so basically add tooltips for the below icons only in the navbar
> 
> <img alt="Screenshot 2022-09-08 at 11 59 14 PM" width="169" src="https://user-images.githubusercontent.com/48400770/189198524-922b7401-7fb6-4c4c-80c5-7794e44421a5.png">

Yes, Exactly💯
