### ISSUE TITLE
Optimizing the Database  (user and project) model

### ISSUE THREAD

**Issue by AdityaPainuli** [rohitdasu/projectmate#105]
### 2. We need to create a user model with it and set up an optional relationship with the project model (database relations will be one - too many ). 

![code](https://user-images.githubusercontent.com/66621672/189338951-c7be0798-3e8f-4453-a10c-537e8be95661.png)

**Comment by RakeshSangem** [comment]
I've just recently referred to the Prisma documentation. So I came to know that `?` makes the field optional. In our case those fields are mandatory fields. So this should be fixed ASAP!

Nice observation @AdityaPainuli .

**Comment by AdityaPainuli** [comment]
If no one is working on this I can pick this issue and solve it today.

**Comment by ykhokhaneshiya** [comment]
@AdityaPainuli @rohitdasu , I have made this change and just updating on the same branch.

**Comment by RakeshSangem** [comment]
> @AdityaPainuli @rohitdasu , I have made this change and just updating on the same branch.

Good job👏

**Comment by leewan-09** [comment]
i working on this task

**Comment by rohitdasu** [comment]
thanks @leewan-09 please let us know if you want anything
