### ISSUE TITLE
[FEATURE] Adding API routes 

### ISSUE THREAD

**Issue by AdityaPainuli** [rohitdasu/projectmate#116]
### Description

for me right now we have to make API routes for - 
1. Adding a user 
2. Creating a project

**Comment by leewan-09** [comment]
While you're doing the API try to fix that RESPONSE TYPE 

![image](https://user-images.githubusercontent.com/60838584/189517965-9471f6d8-33a8-42d8-bc70-11ac805a2ab5.png)

**Comment by rohitdasu** [comment]
@AdityaPainuli

**Comment by AdityaPainuli** [comment]
Ok I will look into this problem

**Comment by AdityaPainuli** [comment]
## I am also thinking of adding a tags model into the project schema file .

### Tag model is going to be - 
>  Many-to-many relationship 
> We can use it to make a filter on the application one tag can have many posts that can have the same tags. 

#### What do you guys think about it?

**Comment by AdityaPainuli** [comment]
> While you're doing the API try to fix that RESPONSE TYPE
> 
> ![image](https://user-images.githubusercontent.com/60838584/189517965-9471f6d8-33a8-42d8-bc70-11ac805a2ab5.png)

Btw where are we going to use it ?

**Comment by rohitdasu** [comment]
> > While you're doing the API try to fix that RESPONSE TYPE
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/60838584/189517965-9471f6d8-33a8-42d8-bc70-11ac805a2ab5.png)
> 
> 
> 
> Btw where are we going to use it ?

In the api response we will be sending in this type

**Comment by AdityaPainuli** [comment]
we can do any on the data field

**Comment by leewan-09** [comment]
> > While you're doing the API try to fix that RESPONSE TYPE
> > ![image](https://user-images.githubusercontent.com/60838584/189517965-9471f6d8-33a8-42d8-bc70-11ac805a2ab5.png)
> 
> Btw where are we going to use it?

we can make class like [this] (https://blog.devgenius.io/nodejs-make-your-api-response-nicely-f562f78cb67)

**Comment by AdityaPainuli** [comment]
![code](https://user-images.githubusercontent.com/66621672/189519776-d009181f-bdaa-4edf-99f6-354cbf95f13f.png)
what you think about it

**Comment by rohitdasu** [comment]
> we can do any on the data field 
> 
> 

No we shouldn't use 'any'

**Comment by leewan-09** [comment]
https://blog.devgenius.io/nodejs-make-your-api-response-nicely-f562f78cb67 
read this

**Comment by rohitdasu** [comment]
Can you implement in this approach @AdityaPainuli  ?

**Comment by AdityaPainuli** [comment]
I will try to do that
