### ISSUE TITLE
[DOCS] create an image for this repository - social preview/Repo card

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#126]
### Description

create an image for this repository - social preview

Whenever we share our repository link this image will be shown as embedded

Image resolution should be 1280x640

See below template

![repository-open-graph-template](https://user-images.githubusercontent.com/48400770/189681347-ca59c84a-a50e-45be-8846-85799047d188.png)

**Comment by flying-solo** [comment]
@rohitdasu I would like to take this issue , and work on it .

**Comment by rohitdasu** [comment]
@flying-solo Hi, we have already got an image for it. but feel free to work on it. will use it if we find your image more attractive 👍

**Comment by rohitdasu** [comment]
join our discord server to meet our team and discuss

**Comment by RakeshSangem** [comment]
Yeah, would love to see your work!
