### ISSUE TITLE
[CHORE] move local dummy data into db

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#132]
### Description

Requirement:
Currently we are getting projects dummy data from local folder. That needs to be changed. We should move that data into database and we should fetch that data through API and bind into projects page.

**Comment by sachdevlaksh** [comment]
Would like to check this out.

**Comment by rohitdasu** [comment]
added you 👍

**Comment by flying-solo** [comment]
@rohitdasu i would like to work on this

**Comment by RakeshSangem** [comment]
> @rohitdasu i would like to work on this

Hey @flying-solo . Thanks for showing interest but I think @sachdevlaksh working on it. Please join our discord server to know more.
