### ISSUE TITLE
[FEATURE] Create Project's detail page [FE]

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#134]
### Description

Create projects details page.

- Detail page contains more info of the project
- User will navigate to `project details page` when he/she clicks on contribute button

**Comment by AdityaPainuli** [comment]
After completing the add-project page front-end I can work on this until someone else wants to work on it ..

**Comment by rohitdasu** [comment]
let me work on it please.

**Comment by AdityaPainuli** [comment]
> let me work on it please.

Ok from my side 👍

**Comment by AdityaPainuli** [comment]
Hey can I work on this issue

**Comment by rohitdasu** [comment]
okay sure, any idea how it should look?

**Comment by AdityaPainuli** [comment]
Not so sure about it but will try to create a basic rough mockup of it and then see how things goes . You have some design or suggestions in your mind please mention it .will try to add them

**Comment by AdityaPainuli** [comment]
Hey, can you be more specific about the component you want on the details page other than the project description, tags, and GitHub repo button .
