### ISSUE TITLE
[FEATURE] create user's profile page [FE]

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#135]
### Description

We need to create a user's profile page
- In user's profile page we display the information about the user.
- User must authenticate with either Google or GitHub in order to access his profile.

## reference image
![profile](https://user-images.githubusercontent.com/107752425/190402927-4bdea10d-9a4c-4644-b952-2119da3b2a86.png)

**Comment by Vishrut19** [comment]
Hey @rohitdasu  can I work/help on this issue ?

**Comment by rohitdasu** [comment]
hey @Vishrut19 
did you see the figma for profile page?

**Comment by yash91989201** [comment]
I am interested to work on this issue , could you please assign it to me ?

**Comment by rohitdasu** [comment]
> I am interested to work on this issue , could you please assign it to me ?

hey, did you check design for it?

**Comment by yash91989201** [comment]
No , I haven't . I could not find the figma file , could you please point me to it . I'll look into it .

**Comment by yash91989201** [comment]
Yeah , I checked it out last night . The design is pretty good, I can implement the required design.

**Comment by yash91989201** [comment]
Could you please assign this issue to me? I can implement the design given in figma.
