### ISSUE TITLE
[Refactor] improve the login UI [FE] 

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#141]
### Description

The current login UI is not looking great. It could be improved.
- so with the help of reference image update the login UI

### Reference image
![Projectmate_login](https://user-images.githubusercontent.com/107752425/190700384-696ca410-ac00-4271-8897-a8ae1de435a6.png)

**Comment by Rounak-28** [comment]
I want to work on this !

**Comment by rohitdasu** [comment]
assigning you. please create a PR when you're done developing it.
