### ISSUE TITLE
[BUG] After successful login, `button` is still showing `join us`

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#150]
### Description

Requirement:

After logging in change the button text from 'Join Us' to 'Explore Projects' and route it to the `/projects` route.

### Screenshots

<img width="357" alt="Screenshot 2022-09-17 at 11 10 43 PM" src="https://user-images.githubusercontent.com/48400770/190869693-246b9404-ba00-4145-874b-b4cedb19c763.png">

**Comment by vishisht08** [comment]
hii @rohitdasu i would contribute in this can u please share the code so that i can make changes accordingly.

**Comment by rohitdasu** [comment]
Hi @vishisht08 could you please join our discord server? you can decide on which ticket you can work with.

**Comment by vishisht08** [comment]
@rohitdasu sure

**Comment by Rounak-28** [comment]
@vishisht08 https://discord.gg/nhjSU8ek
here!
