### ISSUE TITLE
[BUG] improve login card and fix theme issues

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#153]
### Description

Login card UI can be improved
- Login card background not changing according to theme mode.
- Fix inconsistent spacing of the card items
- add border to the login card

### Screenshots

![login UI](https://user-images.githubusercontent.com/107752425/190887728-062ca518-9912-4188-9af1-1c4916fda992.png)

**Comment by Rounak-28** [comment]
I will work on this

**Comment by RakeshSangem** [comment]
Awesome, assigned to you!
