### ISSUE TITLE
[BUG] fix inconsistent sizes of the project card

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#154]
## 1. Fix in consistent sizes of the project card
![project card](https://user-images.githubusercontent.com/107752425/190888191-b247d869-8ca7-44e9-8a37-3242a9ccf49d.png)

## 2. Add border to project card and tech stack chips
![light mode](https://user-images.githubusercontent.com/107752425/190888284-b6344d0a-e59d-41c6-a882-12745c66cd8b.png)

**Comment by vishisht08** [comment]
hii @RakeshSangem i would like to contribute to this issue please assign me this.

**Comment by rohitdasu** [comment]
@vishisht08 assigning to you. feel free to join our discord to get anykind of support.
