### ISSUE TITLE
[BUG] replace 'any' and make strongly typed components

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#178]
### Description

In our app lot of placing we are using `any` type. that's not a good practice. we need help with that. anyone with good typescript experience can fix this. thanks 🙏

**Comment by ctoffanin** [comment]
I can take a look at this if it is ok with you.

**Comment by leewan-09** [comment]
Sure

**Comment by ctoffanin** [comment]
Ok, you can assign it to me.

**Comment by ctoffanin** [comment]
Why was I unassigned from this?

**Comment by leewan-09** [comment]
> Why was I unassigned from this?

Are you working on the task?

**Comment by ctoffanin** [comment]
Yes

**Comment by rohitdasu** [comment]
hey @ctoffanin let us know if you need anything

**Comment by ctoffanin** [comment]
I have a question though.
In `submit.tsx` in the `FromInputs` type there is `coverImage: any;`
I was assuming it's type `string` because of 
```
  <Image
    src={watch('coverImage')}
    alt="project-image"
    className="h-full w-full object-contain"
    layout="fill"
  />
```
but in 
```
<AiFillCloseCircle
  onClick={() => setValue('coverImage', null)}
  size={30}
  style={{
    zIndex: '50',
    cursor: 'pointer',
    position: 'absolute',
    right: 10,
    top: 10,
  }}
/>
```

the value is set by default to null.
If I change the type of `coverImage` to `string | null`, I have an error from the property `src` of `Image`

**Comment by rohitdasu** [comment]
yeah that's the error of `Image` of nextjs

**Comment by rohitdasu** [comment]
I've had the same issue

**Comment by leewan-09** [comment]
if the cover image is null we need to set the default cover image

**Comment by ctoffanin** [comment]
Do you mean to replace the `null` of
`onClick={() => setValue('coverImage', null)}` with the same string of `coverImg:` in the POST's body?

**Comment by leewan-09** [comment]
cover image is optional, right?

**Comment by ctoffanin** [comment]
from what I can see it's optional in the form, but mandatory in zod schema and that is the reason for the default image in the body of the post.

**Comment by leewan-09** [comment]
yep

> from what I can see it's optional in the form, but mandatory in zod schema and that is the reason for the default image in the body of the post.

Yep I noticed that, it is mandatory in Prisma too

**Comment by ctoffanin** [comment]
so either I make a const with the default image URL and I use it for both `body.coverImg` and the `null` in `onClick={() => setValue('coverImage', null)}` or ...

**Comment by leewan-09** [comment]
`type FormInputs = {
  tags: string[];
  projectName: string;
  repositoryLink: string;
  projectDescription: string;
  coverImage: string | null;
};`

` const coverImageValue = watch('coverImage');`


<img width="480" alt="image" src="https://user-images.githubusercontent.com/60838584/193414990-37ec181c-de5d-4784-a80d-048b220d90b5.png">

**Comment by leewan-09** [comment]
we can do like this, You can adjust Zod and Prisma "Cover image as optional"

**Comment by ctoffanin** [comment]
All right, let me commit and make a PR

**Comment by rohitdasu** [comment]
> We can do it like this and you can adjust Zod and Prisma "Cover image as optional".
> 
> So, When we use the cover image to display. We can check it null. If it is null we can show a default image. @rohitdasu @ctoffanin

so it will be handled in FE?
