### ISSUE TITLE
[FEATURE] replace textual navs to icons

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#184]
### Description

replace `discord` and `github` textual navigation to only icons and put it beside the theme toggle. 
 use icons from `react-icons` package. icons should be `FaDiscord` and `FaGithub`

<img width="831" alt="Screenshot 2022-09-27 at 7 53 02 PM" src="https://user-images.githubusercontent.com/48400770/192552938-e128f9aa-4bd0-4f66-b3dc-a0260d5369f2.png">

**Comment by ahmedsilat44** [comment]
@rohitdasu Hey could you assign this to me. I'd like to do this for hacktoberfest. Thanks 😄

**Comment by kashifumair125** [comment]
@rohitdasu hey could you assign this to me .

**Comment by rohitdasu** [comment]
I would suggest you to join the discord server and talk with the devs. Then someone can assign you this issue.
