### ISSUE TITLE
[FEATURE] create a search API

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#186]
### Description

Requirements: 
- Create a search API for the projects
- It should be Fuzzy Search (A fuzzy search searches for text that matches a term closely instead of exactly)
- It should search for a keyword in project name, description and tags

**Comment by rohitdasu** [comment]
<img width="1345" alt="Screenshot 2022-09-30 at 10 57 32 PM" src="https://user-images.githubusercontent.com/48400770/193324460-31036ec2-cd5c-44c4-aca7-e70fef98b213.png">

**Comment by AdityaPainuli** [comment]
For the search bar do you want to search it from project name or tags

**Comment by rohitdasu** [comment]
in the description it's already mentioned. (project name, description and tags - all three)

**Comment by Freedisch** [comment]
Hello @rohitdasu is there anyone working on that? I want to work on that issue

**Comment by rohitdasu** [comment]
yes you can @Freedisch 
did you get the requirements?

**Comment by Freedisch** [comment]
Yes, I got it

**Comment by leewan-09** [comment]
How do you plan to implement the API?

**Comment by Freedisch** [comment]
@leewan-09, There is a module called Fuse.js, never used it before but I think we can use it for the API. Let me go through it and come back

**Comment by leewan-09** [comment]
> 

did you  check out existing APIs

**Comment by Freedisch** [comment]
@leewan-09  Not yet, Do u have one mind I can use? I'm trying to lunch the project, but I keep receiving a seed error 
![image](https://user-images.githubusercontent.com/82499435/193442293-b51b6dac-444f-442e-82bb-3c002ba65c34.png)

**Comment by leewan-09** [comment]
Did you follow the readme file?

**Comment by Freedisch** [comment]
Yes I did, and I set up the mongo URI with atlas

**Comment by leewan-09** [comment]
Would you like to join our discord server. Where we can help you more

**Comment by Freedisch** [comment]
Alright
