### ISSUE TITLE
[FEATURE] add `content` field in the submit page [FE]

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#187]
### Description

Requirements: 
- Add a new field called `Content` below the `cover image`. 
- `Content` should be a rich text editor where user will add markdown and can preview the markdown. (Just like github's comment box)

Note:- Any package suggestions are welcome, we can discuss which one will work well with our application.

**Comment by mau211** [comment]
@rohitdasu Can this be assigned to me?

**Comment by AdityaPainuli** [comment]
I will also want to work on this one .

**Comment by rohitdasu** [comment]
@mau211 would you like to join our discord server? you can get more details there. link in the readme.md file

**Comment by mau211** [comment]
Yes, thank you
