### ISSUE TITLE
[FEATURE] add `content` to the create project API [BE]

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#188]
### Description

Requirement: 
We are adding new field called `content` to the create project submit form. For that we need to update our existing create project API. 

FYI the `content` field will be markdown.

**Comment by RodrigoRVSN** [comment]
Can you assign me?

**Comment by AdityaPainuli** [comment]
Hey can I work on this issue?

**Comment by titusjoyson** [comment]
@rohitdasu if this issue is still not taken I can work on this.

**Comment by rohitdasu** [comment]
> @rohitdasu if this issue is still not taken I can work on this.

sure

**Comment by titusjoyson** [comment]
@rohitdasu pls assign this to me

**Comment by rohitdasu** [comment]
done @titusjoyson
