### ISSUE TITLE
[CHORE] add automatic className sorting for tailwind prettier

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#189]
### Description

Requirement:
Please add prettier plugin tailwindCSS so that classNames will be sorted. It will help increasing the readability for the developers.

Link - https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by RodrigoRVSN** [comment]
Can you assign me?

**Comment by soustab10** [comment]
Can I be assigned to this issue?
