### ISSUE TITLE
[FEATURE] merge homepage + about page [FE]

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#190]
### Description

requirements:
We will remove about section from the Nav menu. It will be now merged with homepage itself. 
- Open for designs. If anyone has any ideas let us know. 

for inspiration we can use [deefang](https://defaang.vercel.app)'s landing page.

**Comment by Prajwal0225** [comment]
👋🏽 Hey, @rohitdasu  

I am very much interested in contributing to this repository. I pretty much understand what you are hoping for so can you assign this issue to me?

**Comment by rohitdasu** [comment]
Hi @Prajwal0225 how are you going to contribute?

**Comment by Vishrut19** [comment]
Hey @rohitdasu  can I work on this issue ?

**Comment by leewan-09** [comment]
@Vishrut19 @Prajwal0225  Would you like to join our Discord server? So that we can explain more about this task.
https://discord.gg/PNRfG2Bm

**Comment by Prajwal0225** [comment]
I will be arranging all the sections one by one.
And when user clicked on perticular section in home screen then it will scroll down to that perticular section 😇.

**Comment by rohitdasu** [comment]
Guys please create PR using your creativity, would love to see ❤️

**Comment by aakashraj01** [comment]
Hey @rohitdasu Would love to contribute in this issue :) .Will you assign me this issue?

**Comment by ginabeki** [comment]
Is this issue available?

**Comment by rohitdasu** [comment]
> Is this issue available?

yes

**Comment by rohitdasu** [comment]
> Hey @rohitdasu Would love to contribute in this issue :) .Will you assign me this issue?

could you create a PR mentioning this issue, thanks

**Comment by rohitdasu** [comment]
Closing this as it's done.
