### ISSUE TITLE
[FEATURE] Add Project Form Validation 

### ISSUE THREAD

**Issue by leewan-09** [rohitdasu/projectmate#191]
### Description

Validation is lacking from the[ Add Project form](https://project-mate.vercel.app/projects/submit) right now. These are the requirements to strengthen our validation.

**Requirements**

- Add validation to `Repository URL`
- Add validation to `upload image` and size limit is **2MB**
- On validation error show red borders to the input fields
- The `description field` should have a minimum of **160 char**.
- Remove animations from forms 
- Replace alert messages with a toast message

**Comment by titusjoyson** [comment]
@leewan-09 I'll take this issue

**Comment by leewan-09** [comment]
Sure 😊

> @leewan-09 I'll take this issue
