### ISSUE TITLE
[FEATURE] Add a loader animation to the submit project page

### ISSUE THREAD

**Issue by leewan-09** [rohitdasu/projectmate#192]
### Description

When we reload the [submit project page](https://project-mate.vercel.app/projects/submit), we can see the loading text. Replace loading text with a `lottie loading animation`.

Lottie Loading Animation
https://lottiefiles.com/search?q=loading&category=animations

<img width="1086" alt="Screenshot 2022-10-01 at 00 44 32" src="https://user-images.githubusercontent.com/60838584/193345248-1d0b5e32-79ba-4221-b319-5668e9f46f0f.png">

**Comment by mehraankush** [comment]
hello i can do that assign it to  me..

**Comment by yadavsairaj** [comment]
Hey can you assign this to me?
