### ISSUE TITLE
[FEATURE] Develop an API to upload images

### ISSUE THREAD

**Issue by leewan-09** [rohitdasu/projectmate#193]
### Description

Currently, there is no API to upload project cover images. Develop an API to upload images to storage buckets.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/60838584/193346978-17012cbb-f56a-4a3c-b5f7-b8fbb3411a79.png">

**Comment by raji2004** [comment]
i would love to be assigned this issue please

**Comment by AdityaPainuli** [comment]
> i would love to be assigned this issue please

Which storage bucket do you have in mind ?

**Comment by raji2004** [comment]
> > i would love to be assigned this issue please
> 
> Which storage bucket do you have in mind ?

idk yet

**Comment by raji2004** [comment]
ok so i will use cloudinary

**Comment by raji2004** [comment]
> ### Description
> Currently, there is no API to upload project cover images. Develop an API to upload images to storage buckets.
> 
> <img alt="image" width="1171" src="https://user-images.githubusercontent.com/60838584/193346978-17012cbb-f56a-4a3c-b5f7-b8fbb3411a79.png">

so i have a problem i cant access this page idk y

**Comment by leewan-09** [comment]
> > ### Description
> 
> > Currently, there is no API to upload project cover images. Develop an API to upload images to storage buckets.
> 
> > 
> 
> > <img alt="image" width="1171" src="https://user-images.githubusercontent.com/60838584/193346978-17012cbb-f56a-4a3c-b5f7-b8fbb3411a79.png">
> 
> 
> 
> so i have a problem i cant access this page idk y

You have to login to access that page. In development environment you can use any password.

**Comment by rohitdasu** [comment]
> > ### Description
> > Currently, there is no API to upload project cover images. Develop an API to upload images to storage buckets.
> > <img alt="image" width="1171" src="https://user-images.githubusercontent.com/60838584/193346978-17012cbb-f56a-4a3c-b5f7-b8fbb3411a79.png">
> 
> so i have a problem i cant access this page idk y

you need to login

**Comment by raji2004** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/105373159/193412140-b85e5694-6413-4d72-9a93-3e801cd92ae9.png)
i tried that its giving me this

**Comment by leewan-09** [comment]
If you follow the README file, it should work.

**Comment by raji2004** [comment]
![Screenshot (97)](https://user-images.githubusercontent.com/105373159/193418216-4763303d-45e0-4e2b-88f4-80869d2175e3.png)
 so i got this error while doing prisma db seed

**Comment by raji2004** [comment]
and can i get the mongodb url?

**Comment by LucioHenrique512** [comment]
@raji2004 you can install mongo on your machine, use a docker image or use in the cloud.
and then you can run prisma commands described in the readme to create db schema and seed it

https://www.mongodb.com/cloud/atlas

**Comment by raji2004** [comment]
> @raji2004 you can install mongo on your machine, use a docker image or use in the cloud. and then you can run prisma commands described in the readme to create db schema and seed it
> 
> https://www.mongodb.com/cloud/atlas

ok

**Comment by raji2004** [comment]
so im using firebase is that ok?

**Comment by raji2004** [comment]
im really sorry but i am unable to do it please assign the task to someone more qualified

**Comment by leewan-09** [comment]
> im really sorry but i am unable to do it please assign the task to someone more qualified

its okay

**Comment by LucioHenrique512** [comment]
@leewan-09, can assign this issue to me?

**Comment by leewan-09** [comment]
> @leewan-09, can assign this issue to me?

Sure, Share your plan with us 😄

**Comment by rohitdasu** [comment]
what about cloudinary?

**Comment by LucioHenrique512** [comment]
I didn't know about this solution, I took a look, I think we can use cloudinary.
