### ISSUE TITLE
[CHORE] Replace fetch api with axios

### ISSUE THREAD

**Issue by leewan-09** [rohitdasu/projectmate#194]
### Description

Replace all fetch APIs with Axios also handle the errors

![image](https://user-images.githubusercontent.com/60838584/193348970-2db621a2-58d9-483a-bb8e-f1b35fad7b87.png)

**Comment by aanchal-fatwani** [comment]
Hi @leewan-09, I would like to work on this issue. Please assign it to me. Thanks.

**Comment by leewan-09** [comment]
> Hi @leewan-09, I would like to work on this issue. Please assign it to me. Thanks.

sure

**Comment by rohitdasu** [comment]
@aanchal-fatwani let me know if you are able to run the app locally. Or you can join our discord server to get help. Link in the readme

**Comment by iamkelv** [comment]
@leewan-09  can you assign the issue for me?

**Comment by leewan-09** [comment]
@aanchal-fatwani are you working on the task?

**Comment by leewan-09** [comment]
> @leewan-09 can you assign the issue for me?

Sure, create a pr

**Comment by Shivank12batra** [comment]
I see no one assigned to this task, can I do this?

**Comment by rohitdasu** [comment]
hi @Shivank12batra this issue has active PR already
