### ISSUE TITLE
Improve About Us Page

### ISSUE THREAD

**Issue by soustab10** [rohitdasu/projectmate#196]
### Description

The current About Us page only shows small icons of the contributors.
![image](https://user-images.githubusercontent.com/95632583/193398877-64ec579c-ddad-44cd-b8cd-ebb7c3e16ec1.png)

 I was thinking of a way of making cards which show their Github (and Linkdedln) profile info when hovered. An example can be found as shown:
![image](https://user-images.githubusercontent.com/95632583/193398868-f248bc95-1102-4a3a-b4fb-79625b2a221e.png)

I would like to work on this if approved.

**Comment by leewan-09** [comment]
We are planning to remove the about page and move this part to the home page

**Comment by soustab10** [comment]
So can I work on implementing the said idea in the Home Page itself? Or do you have other plans for the same.

**Comment by leewan-09** [comment]
https://github.com/rohitdasu/projectmate/issues/190

**Comment by ginabeki** [comment]
can i work on this issue?

**Comment by rohitdasu** [comment]
hi @ginabeki this task is duplicate one. you can find the new task in #190

**Comment by rohitdasu** [comment]
closing this issue as we have another one related to this.
