### ISSUE TITLE
[FEATURE] Search Bar in Projects is flowing out too much!

### ISSUE THREAD

**Issue by bloodmonk7** [rohitdasu/projectmate#198]
### Description

![Screenshot 2022-10-01 150229](https://user-images.githubusercontent.com/48784848/193402971-521e28fe-aa7f-40a8-ac90-e7531bd94fe7.png)
The search bar is flowing more than project tabs below it (in terms of horizon), If both of them are made of equal length horizontally it will look good!

I would love to work and make it look better

**Comment by leewan-09** [comment]
What plans do you have to improve the search bar?

**Comment by bloodmonk7** [comment]
As you can see It's style can be made a bit more clear than this opaque one and border of search bar is going out on x-axis on both sides if it will be aligned with below project tabs it will look good i think. 
I would love suggestions from you as well!
![Screenshot 2022-10-01 150229](https://user-images.githubusercontent.com/48784848/193404377-4c8ae220-e55c-42f8-ac7b-e3a1eb61e712.png)

**Comment by leewan-09** [comment]
Can you create a PR for this? We would love to see it.

**Comment by bloodmonk7** [comment]
Sure, Thank You for allowing me. I am happy as this is my first PR, Thank you for giving me this opportunity
