### ISSUE TITLE
[CHORE] Tags section is overlapping project description

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#217]
### Issue
If the description of project would be long, visitors won't be able read it.

### How it can be solved
- by adding text-overflow property 
- reducing the size of font

### Screenshot
![image](https://user-images.githubusercontent.com/78981177/195384270-b3b27066-d7be-4af6-bdaa-b9c9aff35b76.png)

**Comment by rohitdasu** [comment]
hi @rupali-codes 
how can i replicate this issue? did you make the screen size small?

**Comment by rohitdasu** [comment]
I cannot see actually... but we can definitely take your issue into consideration. Will keep this issue for development so anyone who wants to contribute can fix this issue. @rupali-codes thanks for contributing.
<img width="390" alt="Screenshot 2022-10-12 at 10 16 26 PM" src="https://user-images.githubusercontent.com/48400770/195401389-caae698d-8ef9-4128-afcb-cef4b53ce109.png">

**Comment by rupali-codes** [comment]
My pleasure @rohitdasu, can I take this...?

**Comment by rohitdasu** [comment]
sure @rupali-codes 
please join our discord server too. we can help you out if you need anything while setting up the development environment locally.

**Comment by rupali-codes** [comment]
yeah, sure.

**Comment by rupali-codes** [comment]
Hi @rohitdasu, I thinnk it's specifically on my machine, I've tested with my other system, and it works fine, So I'm closing this issue...Thanks for your help :)
