### ISSUE TITLE
[FEATURE] A good page for github

### ISSUE THREAD

**Issue by Shreejan-35** [rohitdasu/projectmate#219]
### Description

In clicking on github in the menu it directly opens github.com.
But if we make a html page consisting of all the information of the github with stats and graphs that will be good and then we transfer the traffic to github. 
Pls assign the task of making the webpage for github. 
I have some questions as well -
- how to add tags when uploading a project in the website? (It is not specifoed properly how to separate tags)

**Comment by rohitdasu** [comment]
github page outside project details page?
