### ISSUE TITLE
[FEATURE] replace plain text and icon with LOTTIE ANIMATION

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#220]
### Description

Old:
<img width="1024" alt="Screenshot 2022-10-14 at 12 21 34 PM" src="https://user-images.githubusercontent.com/48400770/195781643-0e3df784-3773-4ec4-a6fb-eb67201d311a.png">

New:
<img width="427" alt="Screenshot 2022-10-14 at 12 21 48 PM" src="https://user-images.githubusercontent.com/48400770/195781669-e81b26a6-9907-43e7-9730-e30495758d83.png">

link for the animation json file: https://lottiefiles.com/102335-coming-soon

**Comment by riteshsoni123** [comment]
Hello @rohitdasu I would like to work on this issue. Can you please assign this to me?

**Comment by rohitdasu** [comment]
please create a PR and mention the issue number 👍
