### ISSUE TITLE
[FEATURE] Improve Homepage

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#221]
### Description

Requirement: 
We have a decent home page, where we are displaying basic info about our app and opensource. but want more creativity to it. if anyone has any better UI in mind then please raise a PR.

homepage link - https://project-mate.vercel.app/

**Comment by NNL-Keerthana** [comment]
Hi!!! I am interested to work on this. 
Can you please elaborate on how you want it to look like?

**Comment by rohitdasu** [comment]
Hi @NNL-Keerthana 
We want to improve the UI/UX of the homepage. 
If you have any ideas to improve the UI and make it look modern then please let us know.

**Comment by rohitdasu** [comment]
please join our Discord server to discuss with other team members.

**Comment by rohitdasu** [comment]
> Sure!, Can you pls send the link for the server

here it is - https://discord.com/invite/FQtyMWFZQ9

**Comment by rohitdasu** [comment]
closing this as a new issue created related to this.
