### ISSUE TITLE
[Bug] update the loader lottie animation color

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#224]
### Description

Requirement: 

Update the loader lottie animation to match with the current theme. Current loader animation color looks yellow, which is not quite right. use this color instead - #ff7100

Current loader: 
<img width="485" alt="Screenshot 2022-10-15 at 5 37 07 PM" src="https://user-images.githubusercontent.com/48400770/195985578-291454b0-e61f-43b0-acf5-6be2549391cc.png">

**Comment by Rounak-28** [comment]
@rohitdasu can I do this?

**Comment by rohitdasu** [comment]
sure @Rounak-28
