### ISSUE TITLE
[FEATURE] add filter section in projects page

### ISSUE THREAD

**Issue by jeevikasirwani** [rohitdasu/projectmate#226]
### Description

The website can have tags while choosing projects (for example js, ruby, python) Categorizing projects under these tags make it easy for developers to checkout as per their skill set.

**Comment by rohitdasu** [comment]
Hi @jeevikasirwani we already have tags for project. Did you check in projects tab? there we are showing tags in chips. Let me know if you mean anything else.

**Comment by jeevikasirwani** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/83456541/195997600-337ffccc-2ff0-4763-8164-76401eff4aaa.png)
Maybe something similar to this, the tags on the left side of website.

**Comment by rohitdasu** [comment]
@jeevikasirwani yup it's filter. we have this in our bucket list.

**Comment by rohitdasu** [comment]
Thanks for adding this issue

**Comment by jeevikasirwani** [comment]
> @jeevikasirwani yup it's filter. we have this in our bucket list.

okay great!

**Comment by raazseth** [comment]
Hey, I am interested in working on this project.

Can you please explain how I can get started?

**Comment by rohitdasu** [comment]
Hey @raazseth could you please join our discord server? we can help you out in getting started
