### ISSUE TITLE
[IMPROVEMENT] add card color light gray for light mode.

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#230]
### Description

Requirement: 
change background color for cards in profile page -  light gray color. 

current version: 
<img width="1415" alt="Screenshot 2022-10-17 at 8 37 26 PM" src="https://user-images.githubusercontent.com/48400770/196214792-b3321781-e162-4972-b27b-fedad0e76533.png">

**Comment by RakeshSangem** [comment]
Adding a shadow works best imo. What do you think?

**Comment by rohitdasu** [comment]
> 

how about adding a different color for background? i feel like everything is white here

**Comment by RakeshSangem** [comment]
> how about adding a different color for background - body? i feel like everything is white here

So here, we can reduce the white intensity by using an off white color so that these cards lift up.

**Comment by NnajiChimuanya** [comment]
Assign me this...

**Comment by rohitdasu** [comment]
> Assign me this...

What did you understand and how will you solve this issue?

**Comment by RakeshSangem** [comment]
@rohitdasu So this is a rough idea of how it will look if we use box-shadow.
> Note: just for reference purpose only😁

![Screenshot 2022-10-18 005417](https://user-images.githubusercontent.com/107752425/196265061-f6c43da4-2119-4716-946c-0b66f9ab3359.png)

**Comment by NnajiChimuanya** [comment]
@RakeshSangem  is already on it, so I'll withdraw

**Comment by RakeshSangem** [comment]
> @RakeshSangem is already on it, so I'll withdraw

nope, this issue still open.

**Comment by NnajiChimuanya** [comment]
Ohh, I just realized tailwindcss
i'm more of CSS, Sass SCSS

**Comment by NnajiChimuanya** [comment]
Done @RakeshSangem
