### ISSUE TITLE
[BUG] Project card UI breaks

### ISSUE THREAD

**Issue by leewan-09** [rohitdasu/projectmate#231]
### **Project card UI breaks**

Things to fix
1. long words should break into a new line.  ( **One line for TITLE**)
2. Give a fixed height to the card

![image](https://user-images.githubusercontent.com/60838584/196240879-27701c65-5e68-4cfc-8f19-201c890316ac.png)

###  This is how the card should look like
![image](https://user-images.githubusercontent.com/60838584/196242065-0c7ae34c-169c-4eae-809d-d879a41da789.png)

**Comment by KidesLeo** [comment]
Hi there, I got a quick start on this and found a simple truncate class did the job. I don't think setting a fixed height does anything since all other overflows are dealt with. Should I create a PR?

**Comment by rohitdasu** [comment]
@KidesLeo  yes please, we would like to see

**Comment by KidesLeo** [comment]
![image](https://user-images.githubusercontent.com/39452009/196367507-6342dc8e-4ad5-4d0e-8ef6-f3de56753598.png)
This is how it looks, also checking the author's name in case it overflows.

**Comment by KidesLeo** [comment]
![image](https://user-images.githubusercontent.com/39452009/196367872-c2296738-772c-4b4c-b258-223263725994.png)
Here's the whole page with some overflowing titles and descriptions.

**Comment by rohitdasu** [comment]
@leewan-09

**Comment by leewan-09** [comment]
> ![image](https://user-images.githubusercontent.com/39452009/196367872-c2296738-772c-4b4c-b258-223263725994.png) Here's the whole page with some overflowing titles and descriptions.

this is fine. The title should only have one line.

**Comment by KidesLeo** [comment]
Cheers, PR created.
