### ISSUE TITLE
[CHORE] update axios version to latest

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#234]
### Description

requirement: we have the older version of axios, please upgrade it to latest

**Comment by javamultiplex** [comment]
I would like to work on this. Please assign this task to me

**Comment by rohitdasu** [comment]
hi @javamultiplex please create a PR and mention the issue #

**Comment by javamultiplex** [comment]
@rohitdasu  - In Step4, MONGODB_URI is mentioned. What is the value? I can keep any dummy value or do you have any?

Create an .env file from the .env.template file (copy everything in the .env.template file and put it in the .env file with appropriate values).

MONGODB_URI is the connection string which you'll get from mongodb [for reference]

**Comment by rohitdasu** [comment]
Hi @javamultiplex you'll get the MONGODB_URI (MongoDB Connection String) from mongodb atlas. It's mandatory to have to use our app.

**Comment by javamultiplex** [comment]
@rohitdasu  - ok so you mean to say I need to create a free database in MongoDB atlas?

**Comment by javamultiplex** [comment]
@rohitdasu  - I have setup database on MongoDB atlas but when I am running **npx prisma db push** then getting this error. All configurations look fine to me.  Did you also face same issue ?

Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: cluster0.hp4qfhq.mongodb.net:27017, Type: Unknown, Error: failed to lookup address information: nodename nor servname provided, or not known }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:349
