### ISSUE TITLE
[FEATURE] Improve projects page accessibility

### ISSUE THREAD

**Issue by Olaleye-Blessing** [rohitdasu/projectmate#241]
### Description

The accessibility of the projects page could be improved by using the right tags.

Since it's a list of projects, `ul` should be used instead of `div`.  `li` also should be used instead of the inner `div`.

![Screenshot (138)](https://user-images.githubusercontent.com/70102539/197071726-875fed34-e582-4db9-a71a-432ca1972560.png)

**Comment by rohitdasu** [comment]
@Olaleye-Blessing great suggestion
