### ISSUE TITLE
[FEATURE] add twitter handle icon beside github icon

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#248]
### Description

Requirement: 
* add twitter handle icon beside the github icon.
* onclick it should open a new tab with projectmate's twitter handle
* both mobile version and desktop version navbar should have twitter handle

link: https://twitter.com/projectmateHQ

**Comment by itzwow** [comment]
I would like to work on this issue.
Kindly assign me this issue

**Comment by rohitdasu** [comment]
Please create a PR @itzwow
