### ISSUE TITLE
[BUG] tags not displaying correct value in project details

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#251]
### Description

issue: project tags are not displaying correct values in project details page

### Screenshots

<img width="571" alt="Screenshot 2022-10-22 at 11 06 19 AM" src="https://user-images.githubusercontent.com/48400770/197322368-7193dbbd-9950-4029-81db-d2a39c34d6f2.png">

**Comment by ashwinpadmakumar** [comment]
@rohitdasu Can you please assign me this issue?

**Comment by rohitdasu** [comment]
Hi @ashwinpadmakumar go ahead create a PR and mention the issue number 👍
