### ISSUE TITLE
[FEATURE] create a `Typography` component

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#258]
### Description

Currently in our application we are using texts in random manner. Size mismatch and style mismatch is happening. To fix this issue we need to create a typography component. 

Requirement: 
* Create a typography component
* It should be polymorphic component - see [this](https://www.freecodecamp.org/news/build-strongly-typed-polymorphic-components-with-react-and-typescript/) for reference
* all styles should be customisable
* all appropriate text props should be there

**Comment by rosita-dmello** [comment]
Hi, I'd like to work on this issue. Can you assign it to me?

**Comment by rohitdasu** [comment]
Hi @rosita-dmello please feel free to create a PR and mention the issue number# 👍
