### ISSUE TITLE
[FEATURE] Add Login/Register button in navbar

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#279]
### Description

**Issue 1**
I just experienced something, which is adding a Login/Register button in navbar might lead to great user experience, because when visitor comes to the site and open projects tab, then if they want to Submit their project they have go back to homepage, and login from there, its kinda long and boring step, so I think that adding Register button in navbar would be nice.

**Issue 2**
I found a small typo, here
![image](https://user-images.githubusercontent.com/78981177/208246956-b2d0b2a3-1365-4f96-be56-1c64af9e8c92.png)
It would be better if it gets fixed :)

**Comment by rohitdasu** [comment]
thanks so much @rupali-codes for the feedbacks. will work on those.

**Comment by rupali-codes** [comment]
@rohitdasu can i be assigned? i would love to contribute :D

**Comment by rohitdasu** [comment]
sure 👍 assigning it to you @rupali-codes
