### ISSUE TITLE
[FEATURE] Adding back-to-top button

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#281]
### Description

As the content increases on site, it hard and boring step to scroll back-to-top manually with scrollbar, and espacially in projects page  as number of projects will grows it would be nice to have a back-to-top button.

**Comment by rohitdasu** [comment]
nice idea! would you like to be assigned to this issue?

**Comment by rohitdasu** [comment]
@rupali-codes

**Comment by rupali-codes** [comment]
yes, why not

**Comment by rohitdasu** [comment]
assigned you @rupali-codes

**Comment by RakeshSangem** [comment]
Great catch @rupali-codes 👍
