### ISSUE TITLE
[FEATURE] add sponsorship button

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#286]
### Description

add buymeacoffee button in the app and readme file. 

account to be used: https://www.buymeacoffee.com/

**Comment by harshitdixit14** [comment]
I would like to work on this, can you add more description about this issue. Where exactly the button is to be added.

**Comment by rohitdasu** [comment]
hi @harshitdixit14 sure, you can work on this.
i want the buymeacoffee button at the readme file (probably beside the title) and in the application's topbar(maybe beside the login/submit project button).

let me know if you have more queries

**Comment by Deepu178** [comment]
hi @rohitdasu 
I have added the sponsorship button.
Can you please provide me your link (https://www.buymeacoffee.com/) ?

**Comment by rohitdasu** [comment]
hi @Deepu178 
here is my link - https://www.buymeacoffee.com/rohit.dasu
