### ISSUE TITLE
[DOCS] Improve Database configuration in the README file

### ISSUE THREAD

**Issue by matmont** [rohitdasu/projectmate#290]
### Description

In my opinion, we could improve the README about the DB connection. Just saw that a couple of other folks (yes, me too :rofl: ) had a couple of issues connecting and running all the setup. I think we just need a very simple guide on how to setup MongoDB Atlas. Or at least just write down that we suggest the use of it.

**Comment by rohitdasu** [comment]
Yes, strongly agree with you. 😄

**Comment by rohitdasu** [comment]
@matmont i've assigned the issue to you
