### ISSUE TITLE
[CHORE] Improve code: "fetcher" usage

### ISSUE THREAD

**Issue by matmont** [rohitdasu/projectmate#291]
### Description

I noticed, in a couple of different places, the usage of a "fetcher" variable, something like this:

```
const fetcher = (url: string) => axios.get(url).then((res) => res.data);
```

I spot two issues here:
- This is often put inside the component, but there is no need for that to be created again at every component rendering
- This could be imported form a single point, some file like "utils"

Anyway, I think that kind of stuff could be managed with the `interceptors` that axios offers. I think, if I'm not missing any special case, we could go with that solution instead.

**Comment by rohitdasu** [comment]
@matmont i agree. @leewan-09 @JakubChorzepa  what's your opinion on this?

**Comment by JakubChorzepa** [comment]
Yeah I think extracting it to utils is great idea

**Comment by rohitdasu** [comment]
thanks @JakubChorzepa 

@matmont  i think this can be implemented! assigning this to you.

**Comment by Olaleye-Blessing** [comment]
We can also make use of the [global config](https://swr.vercel.app/docs/global-configuration) that SWR provides. The fetcher can be overridden if `interceptors` are needed.
