### ISSUE TITLE
[FEATURE] redirect user to login page when clicked on Submit Project

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#297]
### Description

Hi, I experienced something new, when user clicks on **Submit Porject** without login, it only shows a pop-up which says **please login/register first**, it would be more better if we can redirect user to login/register page instead.

**Comment by rohitdasu** [comment]
umm, we don't have any login page. do you mean showing login/register modal?

**Comment by rupali-codes** [comment]
yess

**Comment by rohitdasu** [comment]
okay, should i assign it to you?

**Comment by rupali-codes** [comment]
sure @rohitdasu

**Comment by rohitdasu** [comment]
done @rupali-codes
