### ISSUE TITLE
[FEATURE] update styling for Submit project form

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#302]
### Description

As of now inout fields in the form taking comlete width of the page, it would be nice if we can reduce it a bit, or if we can wrap form into a card

current:- 
![image](https://user-images.githubusercontent.com/78981177/209856100-178ee32b-1bb1-4545-a5a3-86ef05ff11fa.png)

**Comment by sdifeo** [comment]
Hi. I would like to help on this issue.
