### ISSUE TITLE
[FEATURE] add an error boundary

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#311]
### Description

Add error boundaries in our nextjs react tree to gracefully handle client-side errors and render a fallback view when they occur.

resource: https://reactjs.org/docs/error-boundaries.html

**Comment by williamssam** [comment]
Hi @rohitdasu, can I work on this issue?

**Comment by rohitdasu** [comment]
> Hi @rohitdasu, can I work on this issue?

Yes, sure

**Comment by rohitdasu** [comment]
assigned you @williamssam
