### ISSUE TITLE
[CHORE] improve SEO

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#324]
### Description

work on SEO, improve and optimise the site. do all necessary stuff

**Comment by rohitdasu** [comment]
i think we should use this package - https://www.npmjs.com/package/next-seo

**Comment by ConradQQ** [comment]
I'd happily work on this if someone isn't already.

**Comment by rohitdasu** [comment]
Sure, go ahead!

**Comment by ConradQQ** [comment]
Sounds good!

**Comment by Olaleye-Blessing** [comment]
@rohitdasu
