### ISSUE TITLE
[CHORE] put Join us links in footer

### ISSUE THREAD

**Issue by rupali-codes** [rohitdasu/projectmate#326]
### Description

Having the links, where it's currently located, is taking too much space unnecessarily. It would be nice if it could be placed in footer.
![image](https://user-images.githubusercontent.com/78981177/212395799-af476554-a8fa-45ef-8199-02c28037a8ca.png)

**Comment by jdomil** [comment]
Hey @rupali-codes , I just submitted a PR. Let me know if this is not exactly what you were referring to.
