### ISSUE TITLE
[FEATURE] show registered users list

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#330]
### Description

Show registered users list -  in the topnavbar and sidenavbar(in mobile) show a navigation button called `mates` and when we click on that it will redirect us to a new page which will list all users/registered users from user table/collection. 

use your creativity in how we can display a list of users in beautiful yet responsive way. thanks

**Comment by Mayuresh0072** [comment]
@rohitdasu @ashwinpadmakumar @ctoffanin Hello, I want to work on this issue, Please assign me this issue. Thanks.

**Comment by rohitdasu** [comment]
@Mayuresh0072 thanks for showing interest on this issue, i've already picked this up. feel free to see other issues. thanks
