### ISSUE TITLE
[FEATURE] create profile page for other user (show projects shared by him/her)

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#334]
### Description

In mates page (https://projectmate.net/user/all) we can see all users/mates. when we click on button on the mate card, it should redirect to user's profile (similar to our profile page - https://projectmate.net/user/profile).

**Comment by williamssam** [comment]
Hi @rohitdasu, I would love to work on this. If I can, pls assign this to me

**Comment by rohitdasu** [comment]
Sure, go ahead!
