### ISSUE TITLE
[FEATURE] ability to edit our projects

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#336]
### Description

in profile page, we have edit button, make it working. user should redirected to submitpage kindof page/ we can reuse that submitpage form component, whatever suits best let's go for it. the form should be populated with the current data and user can modify and update.

**Comment by kumaryogesh17** [comment]
Hi,
I am reaching out to you because I am facing some issues while setting up project. Specifically, I am encountering an error while trying to run a script in project.  if you could provide me with some guidance or suggestions to help me resolve this issue.

![Screenshot 2023-02-26 161532](https://user-images.githubusercontent.com/82561880/221406062-81a715cc-c668-46e2-b155-7da0930093c4.png)

**Comment by JakubChorzepa** [comment]
> Hi, I am reaching out to you because I am facing some issues while setting up project. Specifically, I am encountering an error while trying to run a script in project. if you could provide me with some guidance or suggestions to help me resolve this issue.
> 
> ![Screenshot 2023-02-26 161532](https://user-images.githubusercontent.com/82561880/221406062-81a715cc-c668-46e2-b155-7da0930093c4.png)

Hey, did you pulled latest changes and run `yarn install`?

**Comment by kumaryogesh17** [comment]
> > Hi, I am reaching out to you because I am facing some issues while setting up project. Specifically, I am encountering an error while trying to run a script in project. if you could provide me with some guidance or suggestions to help me resolve this issue.
> > ![Screenshot 2023-02-26 161532](https://user-images.githubusercontent.com/82561880/221406062-81a715cc-c668-46e2-b155-7da0930093c4.png)
> 
> Hey, did you pulled latest changes and run `yarn install`?

Yes

**Comment by JakubChorzepa** [comment]
Ok, please join our discord server and we'll try to figure it out

> > > Hi, I am reaching out to you because I am facing some issues while setting up project. Specifically, I am encountering an error while trying to run a script in project. if you could provide me with some guidance or suggestions to help me resolve this issue.
> > > ![Screenshot 2023-02-26 161532](https://user-images.githubusercontent.com/82561880/221406062-81a715cc-c668-46e2-b155-7da0930093c4.png)
> > 
> > 
> > Hey, did you pulled latest changes and run `yarn install`?
> 
> Yes
Ok, please join our discord server and we'll try to figure it out

**Comment by kumaryogesh17** [comment]
Okay
