### ISSUE TITLE
[FEATURE] filtering tags in backend

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#338]
### Description

Things to do:

currently in the `/projects` page, there is a filter which only filters in the frontend which means it can't filter projects which are not loaded in the frontend/application. we should handle it through backend. 

On every filter change it should hit the backend api and get results and show it in the UI. 

let us know if you have any doubts. Thanks.

**Comment by Deva-1903** [comment]
Can I work on this issue?

**Comment by rohitdasu** [comment]
> Can I work on this issue?

sure

**Comment by Deva-1903** [comment]
Why issues are being closed? @rohitdasu

**Comment by rohitdasu** [comment]
@Deva-1903 as we are updating our app - lot's of features are removed temporarily and will no longer required in near future.
