### ISSUE TITLE
[FEATURE] ditch light mode

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#343]
### Description

let's not complicate the UI with light mode and dark mode - as we have pretty nice dark mode, we should proceed with that only. 

requirement:
1. remove toggle button
2. make the dark mode as the only theme.

**Comment by zvolcsey** [comment]
I removed the `ThemeToggler` component from `TopBar` component. Delete the `ThemeToggler` folder or keep it in the file structure for later?

**Comment by LucianAiolos** [comment]
Was the issue resolved yet?

**Comment by zvolcsey** [comment]
@LucianAiolos Hi! Working on it.
