### ISSUE TITLE
[IMPROVEMENT]: make the tags as a dropdown/autofill

### ISSUE THREAD

**Issue by JasonDsouza212** [rohitdasu/projectmate#355]
## It has a long list of options
- It would be better if the option is not displayed until a single character is entered
- This feature is needed because the option is too long and covers almost the height of the screen
![Screenshot from 2023-02-19 15-04-18](https://user-images.githubusercontent.com/74404894/219940641-1f240064-79c6-41d1-a88a-bee95641a41a.png)

**Comment by rohitdasu** [comment]
Good point

**Comment by Yash636261** [comment]
may be with browser it works well in edge.
![Untitled](https://user-images.githubusercontent.com/98970491/227706034-fc305006-1964-4012-8305-7bc182ca45e4.png)

**Comment by JasonDsouza212** [comment]
really thats a fantastic job

**Comment by JasonDsouza212** [comment]
@Yash636261 Have a look at this project and you can contribute towards it to
https://github.com/JasonDsouza212/free-hit
