### ISSUE TITLE
[FEATURE] - Light theme toggle button

### ISSUE THREAD

**Issue by ujjawaltyagii** [rohitdasu/projectmate#362]
### Description

- I was thinking that we should have a <b>light theme</b> for website and for that we can add a <b>theme toggle button</b> 
so user will be able to switch between themes according to personal preference.

## we can place it in header alongside login button(left side)
![image](https://user-images.githubusercontent.com/115401171/224769767-61f1e458-6663-4d15-ac08-e936859045ad.png)

### what do you think about it ? (open to suggestions)

**Comment by JakubChorzepa** [comment]
Actually, we used to have light theme that worked as you suggest but we decided to remove it at #343
