### ISSUE TITLE
[BUG] inconsistent sidebar width for mobile view

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#376]
### Description

Inconsistent sidebar width in mobile view, it should be same width for all views, for example projects, mates and posts. Please check the attached screenshots for more clarity. Let us know if you have any questions.

### Screenshots

<img width="148" alt="Screenshot 2023-04-22 at 11 45 48 AM" src="https://user-images.githubusercontent.com/48400770/233766471-8aea31c3-e56c-442e-9a85-e8a940225e94.png">
<img width="248" alt="Screenshot 2023-04-22 at 11 45 35 AM" src="https://user-images.githubusercontent.com/48400770/233766473-5f76821a-4830-43e6-95e0-098c4c876382.png">

**Comment by pushkaraj2007** [comment]
@rohitdasu 

I would like to work on this issue, can you please assign this to me?

**Comment by rohitdasu** [comment]
@pushkaraj2007 great! please create a PR after fixing it.

**Comment by pushkaraj2007** [comment]
@rohitdasu, sure!
