### ISSUE TITLE
[FEATURE] Sharing feature should be enable

### ISSUE THREAD

**Issue by theritikchoure** [rohitdasu/projectmate#382]
### Description

While clicking on share option, it is showing error message as below image.

This feature is great, it should be working.

![image](https://user-images.githubusercontent.com/56495602/235488302-5eb297e2-0f8b-4f8d-aac6-84a5d9667d40.png)

**Comment by rohitdasu** [comment]
@theritikchoure Thanks for creating this issue. Appreciated 🙏

**Comment by ashutosh887** [comment]
I would like to work on this @rohitdasu 
Please assign

**Comment by rohitdasu** [comment]
> I would like to work on this @rohitdasu 
> 
> Please assign

Sure, please work on it and create a PR

**Comment by jobayer12** [comment]
@rohitdasu 
When I run the seed command, It throws an error message. I followed the README.md. The `yarn prisma db push` runs properly but the`yarn prisma db seed` command throws an error. Is there anything else I need to do which is not mentioned in the README.md file?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/26854413/236364748-b9160b38-7205-4f84-8151-60bf79d1c7a4.png">

**Comment by rohitdasu** [comment]
@jobayer12 did you get the mongodb uri?

**Comment by ashutosh887** [comment]
@jobayer12 I've been working on this. You want to take this further?

**Comment by rohitdasu** [comment]
@ashutosh887 i think he was getting the issue so he commented. you should keep working on this.

**Comment by ashutosh887** [comment]
Got it @rohitdasu 

cc: @jobayer12 Let me know if you face any difficulty

**Comment by tarunsamanta2k20** [comment]
@jobayer12 Share functionality is not defined in the codebase. If you know,  please clarify over here.

**Comment by rohitdasu** [comment]
@tarunsamanta2k20 the share functionality is not there. We have put a blank function, this will be replaced with the new code.
