### ISSUE TITLE
[BUG] button div issue

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#384]
### Description

button is taking the whole width, it's a simple tailwindCSS fix. beginner friendly issue.

### Screenshots

<img width="1440" alt="Screenshot 2023-05-04 at 11 02 47 AM" src="https://user-images.githubusercontent.com/48400770/236119583-7e3c885f-6dfd-48c9-b12a-63c8e8320a51.png">

**Comment by pushkaraj2007** [comment]
I'm interested in this issue, can you please assign this to me.

**Comment by rohitdasu** [comment]
@pushkaraj2007 done! please create a PR and let us know if you need anything. thanks

**Comment by pushkaraj2007** [comment]
@rohitdasu, sure!

**Comment by pushkaraj2007** [comment]
@rohitdasu 

I'm applying 'items-center' property to the parent div of all elements of the HereoComponent.

Is it right?

**Comment by rohitdasu** [comment]
> @rohitdasu
> 
> I'm applying 'items-center' property to the parent div of all elements of the HereoComponent.
> 
> Is it right?

that works!

**Comment by pushkaraj2007** [comment]
> > @rohitdasu
> > 
> > I'm applying 'items-center' property to the parent div of all elements of the HereoComponent.
> > 
> > Is it right?
> 
> that works!

Absolutely! 

I have created a PR, can you take a look at it?

**Comment by rohitdasu** [comment]
> > > @rohitdasu
> > > I'm applying 'items-center' property to the parent div of all elements of the HereoComponent.
> > > Is it right?
> > 
> > 
> > that works!
> 
> Absolutely!
> 
> I have created a PR, can you take a look at it?

merged already! ✌️
