### ISSUE TITLE
[BUG] color contrast issue fix (WCAG color contrast issue)

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#386]
### Description

**Requirements:**

Our app should pass all the WCAG color contrast checks. I've added a sample screenshot for reference.

Please install WCAG [Color contrast checker](https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf/related?hl=en) extension and fix all the issues in every single page. 
It should pass all the checks in all pages.

### Screenshots

<img width="1440" alt="Screenshot 2023-05-04 at 10 55 52 PM" src="https://user-images.githubusercontent.com/48400770/236282748-8d871f6f-85c2-410a-b9c6-27770e968882.png">

**Comment by Lucif3r-in** [comment]
@rohitdasu Can I work on it?
