### ISSUE TITLE
[FEATURE] create a mates/users page

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#387]
### Description

Requirements:

We already have an API built to get all users data (https://www.projectmate.net/api/user/all) 

We need to just display the users data in a creative way in https://www.projectmate.net/mates page. 
Please create a PR for the same and let us know if you need anything. Thanks

**Comment by rohitdasu** [comment]
Hi @EidanGar thanks for showing your interest on this issue. 

Yes, mates should be displayed in the grid format. It should have enough gap to look good. 

I don't have any strong opinions on the image alignment. You can create a PR - our maintainers will review and suggest you the changes required. 

Thanks

**Comment by Lucif3r-in** [comment]
@EidanGar Are you still working on this issue?

**Comment by Lucif3r-in** [comment]
@rohitdasu I was working on it and I am getting CORS error. Can you guide me what to do further?

**Comment by AryanKhubchandani** [comment]
Hey @rohitdasu, if no one is working on this issue can I take this up?

**Comment by rohitdasu** [comment]
> Hey @rohitdasu, if no one is working on this issue can I take this up?

Sure, you can pick this up
