### ISSUE TITLE
[CHORE] Replace redux with Context API

### ISSUE THREAD

**Issue by JakubChorzepa** [rohitdasu/projectmate#399]
### Description

We'd like to simplify our state management code and reduce boilerplate as our application does not heavily rely on complex state management by replacing Redux with Context API.

**Comment by vatan999** [comment]
Hey, @JakubChorzepa , I want to work on this issue. Please assign it to me.

**Comment by JakubChorzepa** [comment]
Sure, go ahead.

**Comment by vatan999** [comment]
@JakubChorzepa Not yet, I will ask here if I need anything.
