### ISSUE TITLE
[FEATURE] add our project reference in contribute redirect

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#402]
### Description

Currently in the projects page, when we click on contribute button it is redirecting to the repository url. I want to add a reference query to it's url. 

For example: 
`https://github.com/omnigres/omnigres/?ref=projectmate.net`
instead of `https://github.com/omnigres/omnigres`

Let me know if you have any doubts in it. Thanks

**Comment by ThaungThanHan** [comment]
Please let me take care of this issue.

**Comment by rohitdasu** [comment]
> Please let me take care of this issue.

Sure, please create a PR when you are done
