### ISSUE TITLE
[CHORE] Remove unnecessary icons import

### ISSUE THREAD

**Issue by JakubChorzepa** [rohitdasu/projectmate#405]
### Description

In footer and sidebar components there are unnecessary imports of icons like this:
`import * as SiIcon from 'react-icons/si';`

We'd like to remove those imports and replace them with only icons that are used in these components.

**Comment by pewpewnor** [comment]
Hi there, guys! @JakubChorzepa, after playing around with the frontend code, I managed to fix the import. Now, it should be: import { SiDiscord, SiGithub, SiTwitter } from 'react-icons/si';

I've come up with one possible solution that works. I will leave a PR so you guys can review it through the pull request. Let me know if there is a better solution / modifications I can do.

**Comment by pewpewnor** [comment]
For now I'll only do the footer so you guys can check it first.
