### ISSUE TITLE
[BUG] Remove barrel file from component folder due to next.js tree shaking issue

### ISSUE THREAD

**Issue by JakubChorzepa** [rohitdasu/projectmate#408]
### Description

We'd like to remove index.ts file that re-export every component from components folder (this file is called [barrel file](https://dev.to/luispa/how-to-create-barrels-in-typescript-or-javascript-59ma)). We've discovered that this barrel file is causing bundling every component into one big chunk file.

It is discussed deeper on next.js [issue](https://github.com/vercel/next.js/issues/12557).

What needs to be done:
- remove index.ts from `@/components`
- adjust imports across the app that used the `@/components` import

**Comment by AryanKhubchandani** [comment]
Hello @JakubChorzepa, may I work on this issue?

**Comment by rohitdasu** [comment]
> Hello @JakubChorzepa, may I work on this issue?

Hey, could you check any other issues. Jakub is taking this issue if I'm not wrong

**Comment by JakubChorzepa** [comment]
Hey @AryanKhubchandani, you can take the issue if you want, I'll take something else.
