### ISSUE TITLE
[FEATURE] improve side navbar

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#411]
### Description

We can improve a lot to our current side navbar. 

Attached the screenshot and figma link for reference (ignore icons - just for reference, use names property):
https://www.figma.com/file/3v3ckbS8o24Me4L93so4js/projectmate?type=design&node-id=1829-2&mode=design&t=G3QJNaRPK0adS0wT-0
<img width="304" alt="Screenshot 2023-08-05 at 1 04 44 AM" src="https://github.com/rohitdasu/projectmate/assets/48400770/131f433e-3784-4cf5-8e62-ab4e5f36cda0">

- After logging in user should see their avatar with name (it will be in the place of login button)
- when we click on the avatar/name it should open a dropdown menu where we will have signout feature
- `add project` button will be turned into favicon with '+' symbol in mobile view.

**Comment by AryanKhubchandani** [comment]
Hey @rohitdasu, may I work on this?

**Comment by rohitdasu** [comment]
> Hey @rohitdasu, may I work on this?

sure, if you have any doubts in the requirement - please let us know
