### ISSUE TITLE
[BUG] side nav items not active issue

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#416]
### Description

when we click on any nav item it is not changing the text color to active; only icon color changes. also the icon and text alignment is not centred. fix it.

### Screenshots

<img width="260" alt="Screenshot 2023-08-11 at 12 45 05 AM" src="https://github.com/rohitdasu/projectmate/assets/48400770/9df19609-f63f-4233-8957-e28bee74292d">

**Comment by amartyaroy** [comment]
@rohitdasu can you pls assign this issue to me

**Comment by rohitdasu** [comment]
> @rohitdasu can you pls assign this issue to me

sure, please create a PR

**Comment by rohitdasu** [comment]
@amartyaroy any updates on this?
