### ISSUE TITLE
[CHORE] Wrap Project Description in Project Link

### ISSUE THREAD

**Issue by freedompraise** [rohitdasu/projectmate#425]
### Description

While surfing the projects on the site, I instinctively try to open a project by clicking around it's description / name area, but it does nothing. 
I then find out that the link is in a small button below

I suggest linking the project from it's name / description, to aid easier clicking

**Comment by enti-re** [comment]
I think adding the link to the name will be good. I can pick this @rohitdasu

**Comment by rohitdasu** [comment]
anyone interested working on this issue?

**Comment by rohitdasu** [comment]
> I am interested in contributing.

great, go ahead.

**Comment by sudip57** [comment]
Should I wrap the link in the name or description?

**Comment by rohitdasu** [comment]
> Should I wrap the link in the name or description?

I think name sounds perfect.

**Comment by sudip57** [comment]
Yes
