### ISSUE TITLE
[FEATURE] add URL validation using ZOD using Regex [FRONTEND & BACKEND]

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#432]
### Description

In the "Add Project" modal, we have a field "Live URL". It's currently doesn't have URL validation. Use basic URL validation like URL should be starting with https:// or www etc.

<img width="1440" alt="Screenshot 2023-12-15 at 12 00 29 AM" src="https://github.com/rohitdasu/projectmate/assets/48400770/e053da70-26b8-443b-80a2-740a0db8be12">

In the "Profile" page if we goto our own profile, we able to see "Edit Profile" button. Upon clicking on the button it will show a edit profile sheet. There we have - github, linkedin, twitter and website fields. It's currently doesn't have URL validation. Use basic URL validation like URL should be starting with https:// or www etc.  in case of social links like github, twitter etc check the domain as well, if it matches.

<img width="396" alt="Screenshot 2023-12-15 at 12 01 10 AM" src="https://github.com/rohitdasu/projectmate/assets/48400770/21e9f1aa-9ba5-4789-9421-5d36366233cb">
<img width="1440" alt="Screenshot 2023-12-15 at 12 00 51 AM" src="https://github.com/rohitdasu/projectmate/assets/48400770/6b7cb04e-d9fa-4ad8-9742-98b5b17dc39d">

Let us know if you have any doubt. Comment here so that we can assign it to you. :)

**Comment by Akash5908** [comment]
@rohitdasu  If this issue is not assigned can you please assign it to me, I have done this same issue in my recent opensource project wanderlust.

**Comment by rohitdasu** [comment]
> @rohitdasu  If this issue is not assigned can you please assign it to me, I have done this same issue in my recent opensource project wanderlust.

Sure, you can work on it.

**Comment by Akash5908** [comment]
@rohitdasu Added validation using zod in both frontend and backend and made a pull request regarding issue #432

**Comment by Akash5908** [comment]
@rohitdasu You checked my Pr?

**Comment by rohitdasu** [comment]
@Akash5908 i will check later today. Sorry for the delay

**Comment by Akash5908** [comment]
@rohitdasu I solved the build issue and made a new pull request plz check.

**Comment by Akash5908** [comment]
@rohitdasu I solved the issue and made a pull request plz check.
