### ISSUE TITLE
[FEATURE] change page title - EASY TASK

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#433]
### Description

Hi, we need to change the page title of the root index.tsx from `Home | Projectmate` to `Projectmate`.

Let me know if you have any doubts. Thanks :)

**Comment by rohitdasu** [comment]
@mrblackghostt how about this easy task to get started?

**Comment by MrBlackGhostt** [comment]
ya sure i can do that
what is the new title

**Comment by rohitdasu** [comment]
> ya sure i can do that what is the new title

please follow description.

**Comment by MrBlackGhostt** [comment]
I want to contribute more  a little harder than this @rohitdasu
