### ISSUE TITLE
[FEATURE] add infinite load to `mates` page

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#439]
### Description

Instead of showing all the users data at a time, show ~20 at first glance and upon scrolling show more. We already have implemented infinite load in the projects page, need to implement for mates page as well. Instead of modifying existing api, i would strongly advice create another api for the infinite load feature in the backend. 

let me know if you have any doubts. Thank You :)

**Comment by YubaNeupane** [comment]
can i get assigned this issue?

**Comment by rohitdasu** [comment]
> can i get assigned this issue?

Sure :)

**Comment by csagar131** [comment]
hi @rohitdasu  could you assigned me this feature, hope my contribution will add a value to this project...

**Comment by rohitdasu** [comment]
@csagar131 sure, thanks for showing your interest :)

**Comment by csagar131** [comment]
Thanks @rohitdasu

**Comment by csagar131** [comment]
Hi @rohitdasu  i am getting below error while seeding the mongo database, i have tried almost everything available on internet to solve this issue, still getting same error,  could you please help me out here.

yarn run v1.22.21
$ /Users/sagarmochi/Desktop/projectmate/node_modules/.bin/prisma db seed
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rohitdasu** [comment]
@csagar131 are you on discord group? I can have a look at this problem.
