### ISSUE TITLE
[FEATURE] Add "Back to Top" Floating Action Button (FAB)

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#440]
### Description

Current Behavior:
There is no mechanism in place to quickly navigate users back to the top of the page, especially on longer pages with extensive content.

Desired Behavior:
Implement a "Back to Top" feature by adding a Floating Action Button (FAB) that, when clicked, smoothly scrolls the user back to the top of the page. This will enhance user experience, providing a convenient way to navigate to the top without manually scrolling.

**Comment by YubaNeupane** [comment]
can i get assigned this issue?

**Comment by rohitdasu** [comment]
> can i get assigned this issue?

Sure, assigning it to you.

**Comment by YubaNeupane** [comment]
@rohitdasu could you check my PR?

**Comment by FazeenIjaz** [comment]
Hi, Can i do it or is it done?

**Comment by rohitdasu** [comment]
> Hi, Can i do it or is it done?

sure, you can :)
let us know if you need anything

**Comment by FazeenIjaz** [comment]
npx prisma db push is showing error that error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `MONGODB_URI` resolved to an empty string.   
  -->  schema.prisma:10
   |
 9 |   provider = "mongodb"
10 |   url      = env("MONGODB_URI")
   |

Validation Error Count: 1

![Screenshot 2024-01-26 192650](https://github.com/rohitdasu/projectmate/assets/144797618/21babb14-ec8d-45cf-af7b-b4ecc86f11ea)

**Comment by rohitdasu** [comment]
@FazeenIjaz are you able to add the button?

**Comment by FazeenIjaz** [comment]
> @FazeenIjaz are you able to add the button?

@rohitdasu yes, I can add it. In fact, I had also written code for that, but what's about the error shown above?

**Comment by rohitdasu** [comment]
@FazeenIjaz that error is related to the database connection string, you've not provided it so it's throwing that error.

**Comment by FazeenIjaz** [comment]
@rohitdasu The same thing I am asking what should be that string?
Btw I don't need anything related to that database, so is it necessary to run that command, npx prisma db push

**Comment by rohitdasu** [comment]
> @rohitdasu The same thing I am asking what should be that string? Btw I don't need anything related to that database, so is it necessary to run that command, npx prisma db push, Or I can just add that button without any database use?

there's no need in db here. please create a PR

**Comment by FazeenIjaz** [comment]
@rohitdasu I created a PR, please check it out.
