### ISSUE TITLE
[DOCS] improve README.md file 

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#5]
Add a README.md file with instructions to. start the application

**Comment by HKAgrwl** [comment]
Hi, can you assign this issue to me?

**Comment by HKAgrwl** [comment]
I can add pictures of the homepage/frontend so devs know what it looks like when up and running

**Comment by rohitdasu** [comment]
@HKAgrwl good idea but let's add the homepage/landing image later as it's not ready yet. But could you add icons for the tech stack? like you can add Nextjs/React icon beside the React/Nextjs and Nodejs icon beside the nodejs text.

**Comment by rohitdasu** [comment]
add this discord link too - https://discord.gg/M2BMPdku

**Comment by HKAgrwl** [comment]
OK

**Comment by rohitdasu** [comment]
@HKAgrwl assigned it to you. please work on it and raise a PR

**Comment by rohitdasu** [comment]
@HKAgrwl could you please let me know if you can resolve the comments in the PR #15 ?

**Comment by rohitdasu** [comment]
this issue is open to be worked. if anyone interested please create a PR. Thanks
