### ISSUE TITLE
[DOCS] Adding Live Website Screenshots/Video

### ISSUE THREAD

**Issue by krupalitrivedi** [rohitdasu/projectmate#50]
It provides a beautiful look to the ReadMe file and a better understanding to possible users of what they might find when they click on the link.

(This can also work as a good first issue!)

**Comment by rohitdasu** [comment]
Yes, nice idea

**Comment by RakeshSangem** [comment]
In my opinion, we have not ready to display the live website.

**Comment by rohitdasu** [comment]
This can be done later when we release our first MVP version

**Comment by RakeshSangem** [comment]
> This can be done later when we release our first MVP version
> 

Yes, Exactly. For now we are not ready imo.

**Comment by krupalitrivedi** [comment]
Okay! Just a suggestion <3 Whenever you wish to integrate

**Comment by RakeshSangem** [comment]
> Okay! Just a suggestion <3 Whenever you wish to integrate

BTW, nice idea though! Thanks for reminding us⚡

**Comment by rohitdasu** [comment]
@krupalitrivedi i'm assigning this issue to you. You can work on this when our first version releases. 
Join our discord server for more interaction with the team - https://discord.com/invite/M2BMPdku.

**Comment by uday03meh** [comment]
Hi, Can I work on this issue?

**Comment by rohitdasu** [comment]
hi @uday03meh i think we are not ready for this ticket. we'll pick this issue when we complete our first mvp
