### ISSUE TITLE
[BUG] fix hover issue and selected page highlight

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#64]
<img width="316" alt="Screenshot 2022-09-01 at 2 19 28 PM" src="https://user-images.githubusercontent.com/48400770/187873184-d16a3317-25f8-46c6-84e6-b99988e25479.png">

please add hover effect as well as selected route highlight (active route)

**Comment by AdityaPainuli** [comment]
Assign it to me will work on it.

**Comment by rohitdasu** [comment]
done! thanks

**Comment by RakeshSangem** [comment]
It's looks like issue has been resolved, if that's the case please close this issue. @AdityaPainuli @rohitdasu

**Comment by rohitdasu** [comment]
thanks @RakeshSangem
