### ISSUE TITLE
[FEATURE] get data from backend

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#76]
fetch data for home from home api(api/home) and integrate it to landingpage/homepage

**Comment by AdityaPainuli** [comment]
@rohitdasu what do you think if we use hardcoded data for the home page?

**Comment by AdityaPainuli** [comment]
yeah sure..

**Comment by AdityaPainuli** [comment]
Hey @rohitdasu  do you have any lead on this or should we close this for now?
