### ISSUE TITLE
[DOCS] add about/about-us text section for the app

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#80]
Mainly focus on 
* What we do
* What's the current issue we are solving
* How we got the idea to solve it
* small shoutout to our contributors

**Comment by leewan-09** [comment]
Are we going to use markdown?

**Comment by rohitdasu** [comment]
yeah that would be great. we can directly send data from backend.

**Comment by Kaushik-Iyer** [comment]
Can I work on this?

**Comment by rohitdasu** [comment]
i think there is a new issue related to this. closing this one.
