### ISSUE TITLE
[FEATURE] add project api (POST api)

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#81]
Create a post api for adding projects to the mongoDB database

**Comment by leewan-09** [comment]
I would like to do this task. Could you elaborate a little more?
@rohitdasu

**Comment by rohitdasu** [comment]
sure, would you like to join our discord server? we can explain you better there.
https://discord.gg/SJc3QPpYzU

**Comment by rohitdasu** [comment]
closing this task as @AdityaPainuli created a new issue related to it.
