### ISSUE TITLE
[FEATURE] show auth screen on click 'contribute' button on projects page

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#82]
auth screen should show when user is unauthenticated and clicks on 'contribute' button

**Comment by dpd007** [comment]
Give me this task @rohitdasu. I'll do.

**Comment by rohitdasu** [comment]
assigned it 👍

**Comment by rohitdasu** [comment]
@AdityaPainuli - we should not disable the contribute button, instead we should show login modal

any other opinion on this issue ?
@RakeshSangem

**Comment by RakeshSangem** [comment]
> @AdityaPainuli - we should not disable the contribute button, instead we should show login modal
> 
> any other opinion on this issue ? @RakeshSangem

Yeah! We can display the login component when the user clicks the contribute button. In that login component, can we also add a phrase like `login to continue`?

**Comment by AdityaPainuli** [comment]
> > @AdityaPainuli - we should not disable the contribute button, instead we should show login modal
> > 
> > any other opinion on this issue ? @RakeshSangem
> 
> Yeah! We can display the login component when the user clicks the contribute button. In that login component, can we also add a phrase like `login to continue`?

Yup it can be on that also .

**Comment by rohitdasu** [comment]
Ok then i'm changing the issue title as we got different way to handle this issue

**Comment by AdityaPainuli** [comment]
Assign this one to me I'll handle it
