### ISSUE TITLE
[FEATURE] add infinite scroll to the projects page [FE]

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#86]
### Description

the idea is to not use pagination where the UX would be not that great. Infinite Scroll is the new trend so let's implement this. The data should be getting from backend and on each `scroll down to bottom` it will fetch some extra data to the projects array. Let's discuss it if you have any doubts. 

**Note**
> This is only for frontend, backend implementation will be in different `github issue`

**Comment by rohitdasu** [comment]
i think it should be similar to what github has. 
when we reach at the bottom, there should be a button called "load more" and onclick it will add more data to the list. 

<img width="793" alt="Screenshot 2022-09-27 at 9 00 23 PM" src="https://user-images.githubusercontent.com/48400770/192569725-91cf6af0-ffc8-4c35-8ac0-ae0a202d97e6.png">

**Comment by RakeshSangem** [comment]
> i think it should be similar to what github has. when we reach at the bottom, there should be a button called "load more" and onclick it will add more data to the list.


Yeah, it would be great if we implement like this. Because the loading time can be reduced, right?
