### ISSUE TITLE
[FEATURE] add project form

### ISSUE THREAD

**Issue by rohitdasu** [rohitdasu/projectmate#94]
### Description

The `add project` form should open when user clicks on the `add project` button which is present in the fab action button.

**Comment by AdityaPainuli** [comment]
what do you think about creating our own form?

**Comment by rohitdasu** [comment]
yeah for now we can use basic forms but later we can think of quill or something else 👍

**Comment by RakeshSangem** [comment]
Yeah, at first we should make it functional. We can improve it in future.

**Comment by rohitdasu** [comment]
Changing the issue title as we are not going to implement quill-forms now. we are going to use normal forms as of now

**Comment by AdityaPainuli** [comment]
I will work on it. assigning it to me
