### ISSUE TITLE
[FEATURE] Integrate Prisma MongoDB into NextJS

### ISSUE THREAD

**Issue by RakeshSangem** [rohitdasu/projectmate#95]
### Description

Check references down below:

- **How to setup Prisma+MongoDB**: https://itnext.io/using-prisma-orm-with-mongodb-in-next-js-e42b1f7543e6

- **Prisma Official Docs**: https://www.prisma.io/docs/concepts/database-connectors/mongodb

**Comment by ykhokhaneshiya** [comment]
@rohitdasu @RakeshSangem , Please assign this to me.

**Comment by rohitdasu** [comment]
Done! @ykhokhaneshiya feel free to create a PR
